services:
  server:
    build:
      context: ./server
      target: prod
    volumes:
      - ./server:/app
      - logs:/app/logs
    ports:
      - '8080:80'
    env_file:
      - .env.prod
    # environment:
    #   - DB_SERVER=${DB_SERVER}
    #   - DB_USER=${DB_USER}
    #   - DB_PASSWORD=${DB_PASSWORD}
    #   - DB_NAME=${DB_NAME}

volumes:
  db_data:
  logs:
